messages:
  prefix: "&8[&bBsruCrates&8] "
  no_permission: "&cคุณไม่มีสิทธิ์ใช้งานคำสั่งนี้"
  player_not_found: "&cไม่พบผู้เล่น '{player}'"
  crate_type_not_found: "&cไม่พบกล่องประเภท '{type}'"
  key_given: "&aคุณได้ให้ {key_name} &aจำนวน {amount} ชิ้นแก่ {player}"
  key_received: "&aคุณได้รับ {key_name} &aจำนวน {amount} ชิ้น!"
  inventory_full: "&cช่องเก็บของของ {player} เต็ม ไอเทมจึงถูกดรอปลงบนพื้น"
  set_crate_success: "&aตั้งค่าบล็อกที่มองอยู่ให้เป็นกล่อง '{type}' สำเร็จ"
  remove_crate_success: "&aลบกล่อง ณ ตำแหน่งนี้สำเร็จ"
  not_a_crate: "&cบล็อกนี้ไม่ใช่กล่อง"
  look_at_block: "&cคุณต้องมองไปที่บล็อก"
  no_key: "&cคุณมีกุญแจหรือแต้มไม่เพียงพอสำหรับเปิดกล่องนี้!"
  reward_received: "&aคุณได้รับ {reward_name}&a!"
  reload_success: "&aรีโหลดคอนฟิกสำเร็จ!"
  cannot_place_key: "&cคุณไม่สามารถวางกุญแจพิเศษนี้ได้!"

# [เพิ่ม] การตั้งค่าเสียงใหม่ทั้งหมด
sounds:
  select_item: "ui.button.click"
  cancel_purchase: "entity.villager.no"
  reward_received: "entity.experience_orb.pickup"
  no_key: "entity.villager.no"