name: bsruCrates
version: 3.5.0
main: com.bsru.bsruCrates
api-version: '1.18'
author: Nattapat2871
description: A custom key-based crate system with points support.
softdepend: [PlaceholderAPI]

commands:
  bsrucrates:
    description: Main command for the bsruCrates plugin.
    aliases: [bcrates]

permissions:
  bsrucrates.admin:
    description: Allows usage of all admin commands for bsruCrates.
    default: op
  bsrucrates.use:
    description: Allows players to use crates.
    default: true